//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapurBucyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class bahan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bahan()
        {
            this.detail_penggunaan = new HashSet<detail_penggunaan>();
            this.pembelian_bahan = new HashSet<pembelian_bahan>();
        }
    
        public int id_bahan { get; set; }
        public string nama_bahan { get; set; }
        public Nullable<int> harga_bahan { get; set; }
        public Nullable<int> stock_bahan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_penggunaan> detail_penggunaan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pembelian_bahan> pembelian_bahan { get; set; }
    }
}
