//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapurBucyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class bahan_nasi
    {
        public int id_bahan_nasi { get; set; }
        public int id_penggunaan { get; set; }
        public int id_nasi { get; set; }
        public Nullable<int> jumlah_nasi { get; set; }
        public Nullable<int> laba_rugi { get; set; }
    
        public virtual penggunaan penggunaan { get; set; }
        public virtual nasi nasi { get; set; }
    }
}
