//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapurBucyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_penjualan
    {
        public int id_detail_pembelian { get; set; }
        public int id_penjualan { get; set; }
        public int id_nasi { get; set; }
        public Nullable<int> jumlah_nasi { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual nasi nasi { get; set; }
        public virtual penjualan penjualan { get; set; }
    }
}
