//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapurBucyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_penggunaan
    {
        public int id_detail { get; set; }
        public int id_penggunaan { get; set; }
        public int id_bahan { get; set; }
        public Nullable<int> jumlah_bahan { get; set; }
        public Nullable<int> total_bahan { get; set; }
    
        public virtual bahan bahan { get; set; }
        public virtual penggunaan penggunaan { get; set; }
    }
}
