//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapurBucyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class nasi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nasi()
        {
            this.bahan_nasi = new HashSet<bahan_nasi>();
            this.detail_penjualan = new HashSet<detail_penjualan>();
        }
    
        public int id_nasi { get; set; }
        public string nama_nasi { get; set; }
        public Nullable<int> harga_nasi { get; set; }
        public Nullable<int> stock_nasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahan_nasi> bahan_nasi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_penjualan> detail_penjualan { get; set; }
    }
}
